version: '3.8'
name: base_services


services:
  minio:
    image: quay.io/minio/minio
    container_name: ${COMPOSE_PROJECT_NAME}_minio
    restart: unless-stopped
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    networks:
      - services-network
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ${MINIO_DATA_DIR}:/data
    command: server /data --console-address ":9001"

  mongo:
    image: mongo:latest
    container_name: ${COMPOSE_PROJECT_NAME}_mongo
    ports:
      - "${MONGO_PORT}:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGODB_DATA_DIR: ${MONGODB_DATA_DIR}
      MONDODB_LOG_DIR: ${MONDODB_LOG_DIR}
    networks:
      - services-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

    volumes:
      - type: bind
        source: ${MONGO_DATA_DIR}
        target: ${MONGODB_DATA_DIR}

networks:
  services-network:
    driver: bridge
