name: minio_service

services:
  minio:
    image: quay.io/minio/minio
    container_name: ${COMPOSE_PROJECT_NAME}_minio
    restart: unless-stopped
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ${MINIO_DATA_DIR}:/data
    command: server /data --console-address ":9001"
