name: Deploy Prometheus Service

on:
  workflow_dispatch:
    inputs:
      compose_project_name:
        description: 'Override COMPOSE_PROJECT_NAME'
        required: false
        default: 'pz_mothership'

jobs:
  deploy-prometheus:
    uses: ./.github/workflows/deploy-services.yml
    with:
      compose_project_name: ${{ inputs.compose_project_name }}
      service: prometheus
    secrets: inherit
