name: Deploy NVIDIA DCGM Exporter Service

on:
  workflow_dispatch:
    inputs:
      compose_project_name:
        description: 'Override COMPOSE_PROJECT_NAME'
        required: false
        default: 'pz_mothership'

jobs:
  deploy-nvidia-dcgm-exporter:
    uses: ./.github/workflows/deploy-services.yml
    with:
      compose_project_name: ${{ inputs.compose_project_name }}
      service: nvidia-dcgm-exporter
    secrets: inherit
