name: Deploy MongoDB Service

on:
  workflow_dispatch:
    inputs:
      compose_project_name:
        description: 'Override COMPOSE_PROJECT_NAME'
        required: false
        default: 'pz_mothership'

jobs:
  deploy-mongo:
    runs-on: ubuntu-latest
    env:
      COMPOSE_PROJECT_NAME: ${{ github.event.inputs.compose_project_name }}
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      MONGO_INITDB_DATABASE: ${{ secrets.MONGO_INITDB_DATABASE }}
      MONGODB_DATA_DIR: ${{ secrets.MONGODB_DATA_DIR }}
      MONDODB_LOG_DIR: ${{ secrets.MONDODB_LOG_DIR }}
      MONGO_PORT: ${{ secrets.MONGO_PORT }}
      MONGO_DATA_DIR: ${{ secrets.MONGO_DATA_DIR }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build MongoDB image
      run: |
        docker-compose -f deployments/docker-compose.yml build mongo || echo "No build context; using upstream image"

    - name: Deploy MongoDB service
      run: |
        docker-compose -f deployments/docker-compose.yml up -d mongo
