name: Deploy Node Exporter Service

on:
  workflow_dispatch:
    inputs:
      compose_project_name:
        description: 'Override COMPOSE_PROJECT_NAME'
        required: false
        default: 'pz_mothership'
      service:
        description: 'Service name to deploy'
        required: false
        default: 'node_exporter'

jobs:
  deploy-node-exporter:
    uses: ./.github/workflows/deploy-services.yml
    with:
      compose_project_name: ${{ inputs.compose_project_name }}
      service: ${{ inputs.service }}
    secrets: inherit
