name: Docker Image CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Docker image tag
      run: echo Docker image tag "${{ vars.DOCKER_REGISTRY_REPO }}:${{ github.ref_name }}"
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ vars.DOCKER_REGISTRY_REPO }}:${{ github.ref_name }}
        cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY_REPO }}:${{ github.ref_name }}
        cache-to: type=inline
